---
# tasks file for worker
- name: Sandbox the script
  file: path=/opt/concourse-ci/worker state=directory
- name: Transfer the script
  copy: src=installer.sh dest=/opt/concourse-ci/worker/installer.sh mode=0777
- name: Transfer the file used by the script
  copy: src=concourse-worker.service dest=/opt/concourse-ci/worker/concourse-worker.service mode=0644
- name: Transfer the file used by the script
  copy: src=tsa_host_key.pub dest=/opt/concourse-ci/worker/tsa_host_key.pub mode=0400
- name: Transfer the file used by the script
  copy: src=worker_key.pem dest=/opt/concourse-ci/worker/worker_key.pem mode=0400
- name: Transfer the file used by the script
  template: src=worker_environment dest=/opt/concourse-ci/worker/worker_environment mode=0644
- name: Execute the script
  command: sh /opt/concourse-ci/worker/installer.sh
  register: installer
  become: true
  args:
    chdir: /opt/concourse-ci/worker
    creates: /opt/concourse-ci/worker/installed
  become_user: root
- name: Debug the script
  debug: var=installer
