---
#- name: Hello Web
#  hosts: web
#  roles:
#    - role: web
#- name: Hello DB
#  hosts: db
#  roles:
#    - role: db
#- name: Hello Worker
#  hosts: worker
#  roles:
#    - role: worker
- name: Hello Vault
  hosts: vault
  roles:
    - role: vault
