# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#  config.vm.define "web" do |d|
#    d.vm.box = "ubuntu/xenial64"
#    d.vm.box_version = "20170731.0.0"
#    d.vm.box_check_update = false
#    d.vm.network "forwarded_port", guest: 8080, host: 8080
#    d.vm.network "private_network", ip: "192.168.33.101"
#    d.vm.provider "virtualbox" do |p|
#      p.cpus = "1"
#      p.memory = "1024"
#    end
#  end
#
#  config.vm.define "db" do |d|
#    d.vm.box = "ubuntu/xenial64"
#    d.vm.box_version = "20170731.0.0"
#    d.vm.box_check_update = false
#    d.vm.network "private_network", ip: "192.168.33.102"
#    d.vm.provider "virtualbox" do |p|
#      p.cpus = "1"
#      p.memory = "1024"
#    end
#  end
#
#  config.vm.define "worker" do |d|
#    d.vm.box = "ubuntu/xenial64"
#    d.vm.box_version = "20170731.0.0"
#    d.vm.box_check_update = false
#    d.vm.network "private_network", ip: "192.168.33.103"
#    d.vm.provider "virtualbox" do |p|
#      p.cpus = "1"
#      p.memory = "1024"
#    end
#  end

  config.vm.define "vault" do |d|
    d.vm.box = "ubuntu/xenial64"
    d.vm.box_version = "20170731.0.0"
    d.vm.box_check_update = false
    d.vm.network "private_network", ip: "192.168.33.104"
    d.vm.provider "virtualbox" do |p|
      p.cpus = "1"
      p.memory = "1024"
    end
  end
end
