---
# tasks file for web
- name: Transfer the script
  copy: src=installer.sh dest=/tmp/installer.sh mode=0777
- name: Execute the script
  command: sh /tmp/installer.sh
  register: installer
  become: true
  become_user: root
- name: Debug the script
  debug: var=installer
