---
stub:
  director-uuid: b632f67b-b291-47c1-9a0c-4ff3c5ecf53a
  concourse-vip: 192.168.210.28

name: concourse-ci

director_uuid: (( stub.director-uuid ))

releases:
- name: concourse
  url: https://bosh.io/d/github.com/concourse/concourse?v=2.7.0
  sha1: 826932f631d0941b3e4cc9cb19e0017c7f989b56
  version: latest
- name: garden-runc
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.3.0
  sha1: 816044289381e3b7b66dd73fbcb20005594026a3
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: default
  stemcell: trusty
  azs: [default]
  networks:
  - name: private
    default: [dns, gateway]
  - name: public
    static_ips:
    - (( stub.concourse-vip ))
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: (( "http://" stub.concourse-vip ":8080" ))

      basic_auth_username: admin
      basic_auth_password: admin

      # replace with your SSL cert and key
      #tls_cert: REPLACE_ME
      #tls_key: REPLACE_ME

      postgresql_database: &atc_db atc
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  vm_type: default
  stemcell: trusty
  persistent_disk_type: default
  azs: [default]
  networks: [{name: private}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        role: admin
        password: admin

- name: worker
  instances: 1
  vm_type: large
  stemcell: trusty
  azs: [default]
  networks: [{name: private}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
