---
# tasks file for db
- name: Sandbox the script
  file: path=/opt/concourse-ci/db state=directory
- name: Transfer the script
  copy: src=installer.sh dest=/opt/concourse-ci/db/installer.sh mode=0777
- name: Execute the script
  command: sh /opt/concourse-ci/db/installer.sh
  register: installer
  become: true
  args:
    chdir: /opt/concourse-ci/db
    creates: /opt/concourse-ci/db/installed
  become_user: root
- name: Debug the script
  debug: var=installer
